"""Private subprocess entry; trusted handler files are generated by PythonFunctionAdapter."""

import json
import sys
from pathlib import Path
from typing import cast

# Exact untyped boundary: only private maintainer-generated callback serialization.
import cloudpickle  # type: ignore[import-untyped]
from pydantic import JsonValue, TypeAdapter

from coastmas.adapters.runtime import Handler


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("private runner expects three file arguments")
    schema = TypeAdapter(dict[str, JsonValue])
    with Path(sys.argv[1]).open("rb") as source:
        handler = cast(Handler, cloudpickle.load(source))
    inputs = schema.validate_json(Path(sys.argv[2]).read_text())
    parameters = schema.validate_json(Path(sys.argv[3]).read_text())
    result = schema.validate_python(handler(inputs, parameters))
    print(json.dumps(result, allow_nan=False))


if __name__ == "__main__":
    main()
