import {test,expect} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {evidenceDirectory,evidencePath} from './evidence';

test('indicator picker freezes a real recipe, computes native pixels and preserves task context',async({page})=>{
  test.setTimeout(120000);
  if(!process.env.COASTMAS_NEXT_TEST_URL?.endsWith(':58013'))throw new Error('isolated environment only');
  const access=JSON.parse(await readFile(process.env.COASTMAS_NEXT_ACCESS_FILE!,'utf8'));
  await mkdir(evidenceDirectory,{recursive:true});await page.setViewportSize({width:1440,height:900});
  await page.goto('/research');await page.getByLabel('邮箱',{exact:true}).fill(access.email);await page.getByLabel('密码',{exact:true}).fill(access.password);await page.getByRole('button',{name:'登录',exact:true}).click();
  await expect(page.getByRole('link',{name:'工作台',exact:true})).toBeVisible();
  const session=await(await page.request.get('/api/session')).json(),headers={'X-CSRF-Token':session.csrf};
  const project=await(await page.request.post('/api/projects',{headers,data:{name:'内置指标工程验收 '+Date.now()}})).json();
  const task=await(await page.request.post('/api/tasks',{headers,data:{project_id:project.id,goal:'comprehensive-assessment',title:'内置指标操作工程夹具'}})).json();
  await page.goto(`/tasks/${task.id}?project=${project.id}`);
  await page.getByRole('button',{name:/^指标 ·/}).click();
  const picker=page.getByRole('region',{name:'指标选择器',exact:true});await expect(picker).toBeVisible();
  for(const label of ['科学含义','算法入口','参数Schema','空间尺度'])await expect(picker.getByLabel(label)).toHaveCount(0);
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await picker.getByRole('textbox',{name:'搜索指标'}).fill('NDVI');
  await picker.getByRole('button',{name:'补充数据',exact:true}).click();
  const importer=page.getByRole('dialog',{name:'添加研究输入'});await expect(importer).toBeVisible();
  await importer.getByLabel('选择并导入资料',{exact:true}).setInputFiles('/Users/quanyiming/Projects/CoastMAS/next/artifacts/master-20260925/engineering-red-nir.tif');
  await expect(page.getByRole('tab',{name:'输入 1',exact:true})).toBeVisible();await importer.getByRole('button',{name:'关闭',exact:true}).click();
  await expect(picker).toContainText('当前数据满足');
  const selectedReply=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/v1/tasks/${task.id}/indicators`&&r.request().method()==='POST');
  await picker.getByRole('button',{name:'添加',exact:true}).click();
  const selectedResponse=await selectedReply;expect(selectedResponse.status()).toBe(200);const selected=await selectedResponse.json();
  expect(selectedResponse.request().postDataJSON().items).toEqual([{indicator_id:'indicator.ndvi',parameters:{}}]);
  await expect(page.getByRole('status',{name:'图层就绪',exact:true})).toBeVisible();
  await page.mouse.move(10,10);
  await page.screenshot({path:evidencePath('indicator-ready-1440.png')});
  const runningReply=page.waitForResponse(r=>r.url().includes('/indicators/')&&r.url().endsWith('/execute'));
  await picker.getByRole('button',{name:'计算NDVI',exact:true}).click();const runResponse=await runningReply;expect(runResponse.status()).toBe(202);const job=await runResponse.json();
  await expect.poll(async()=> (await page.request.get(`/api/jobs/${job.id}/result`)).status()).toBe(200);
  const result=await(await page.request.get(`/api/jobs/${job.id}/result`)).json();
  expect(result.data.statistics.total_pixels).toBe(6);expect(result.data.statistics.valid_pixels).toBe(4);
  expect(result.manifest.method.definition.algorithm_version).toBe('spectral/1.0.0');
  const download=await page.request.get(`/api/jobs/${job.id}/artifacts/0/download`);expect(download.status()).toBe(200);
  const bytes=await download.body();expect(createHash('sha256').update(bytes).digest('hex')).toBe(result.data.files[0].sha256);
  await writeFile(evidencePath('indicator.tif'),bytes);
  const coordinate=JSON.parse(await readFile('/Users/quanyiming/Projects/CoastMAS/next/artifacts/master-20260925/engineering-location.json','utf8'));
  const inspect=await page.request.post(`/api/jobs/${job.id}/artifacts/0/inspect`,{headers,data:{...coordinate,band:1}});
  expect(inspect.status()).toBe(200);const pixel=await inspect.json();expect(pixel.value).toBeCloseTo(.5,12);
  await expect(page.locator('.research-result .maplibregl-canvas')).toBeVisible();
  const clickedReply=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/jobs/${job.id}/artifacts/0/inspect`&&r.request().method()==='POST');
  await page.locator('.research-result .maplibregl-canvas').click();
  const clicked=await (await clickedReply).json();expect(clicked.sha256).toBe(result.data.files[0].sha256);
  await expect(page.getByRole('region',{name:'点查结果',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'关闭右侧面板',exact:true}).click();
  await page.getByRole('button',{name:'样式',exact:true}).click();
  await expect(page.getByRole('checkbox',{name:'显示地图图例',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'关闭右侧面板',exact:true}).click();
  await page.screenshot({path:evidencePath('indicator-result-1440.png')});
  for(const size of [{width:1366,height:768},{width:1920,height:1080},{width:2560,height:1440}]){
    await page.setViewportSize(size);await expect(page.locator('.research-result .maplibregl-canvas')).toBeVisible();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.mouse.move(10,10);await page.screenshot({path:evidencePath(`indicator-result-${size.width}.png`)});
  }
  await page.reload();await expect(page.locator('.research-result .maplibregl-canvas')).toBeVisible();
  const persisted=await(await page.request.get(`/api/tasks/${task.id}`)).json();
  expect(persisted.draft.options.indicators[0].selection_id).toBe(selected.items[0].selection_id);
  expect((await(await page.request.get(`/api/projects/${project.id}/tasks`)).json()).length).toBe(1);
  await writeFile(evidencePath('indicator-flow.json'),JSON.stringify({project:project.id,task:task.id,job:job.id,selected,pixel,ui_pixel:clicked,manifest:result.manifest,statistics:result.data.statistics,download_sha256:result.data.files[0].sha256,actions:{indicator_selections:1,technical_fields_entered:0,compute_clicks:1,uploads:1},origin_kind:'engineering_fixture'},null,2));
});
