import { test, expect } from '@playwright/test';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { evidenceDirectory, evidencePath } from './evidence';

test('T08 method draft to fixed application, task import and actual numeric output', async ({page}) => {
 test.setTimeout(150000);
 if(!process.env.COASTMAS_NEXT_TEST_URL?.endsWith(':58013')) throw new Error('isolated environment only');
 const access=JSON.parse(await readFile(process.env.COASTMAS_NEXT_ACCESS_FILE!,'utf8'));
 const before=JSON.parse(await readFile('/Users/quanyiming/Projects/CoastMAS/next/artifacts/import-method-20260924/before2/T01-baseline.json','utf8'));
 await mkdir(evidenceDirectory,{recursive:true}); await page.setViewportSize({width:1440,height:900});
 const requests:unknown[]=[];
 page.on('response',async r=>{if(r.url().includes('/api/')&&['PUT','POST'].includes(r.request().method())&&!/session|parts/.test(r.url()))requests.push({path:new URL(r.url()).pathname,status:r.status(),body:r.request().headers()['content-type']?.includes('application/json')?r.request().postDataJSON():undefined});});
 await page.goto('/methods?project='+before.project);await page.getByLabel('邮箱',{exact:true}).fill(access.email);await page.getByLabel('密码',{exact:true}).fill(access.password);await page.getByRole('button',{name:'登录',exact:true}).click();
 await expect(page.getByRole('link',{name:'工作台',exact:true})).toBeVisible();
 const login=await(await page.request.get('/api/session')).json(); const headers={'X-CSRF-Token':login.csrf};
 const newProject=await(await page.request.post('/api/projects',{headers,data:{name:'联合链工程验收 '+Date.now()}})).json();before.project=newProject.id;
 const fresh=await(await page.request.post('/api/projects/'+before.project+'/method-workspaces',{headers,data:{definition:before.save.persisted.definition}})).json();before.workspace=fresh.id;
 await page.goto('/methods?project='+before.project);await page.getByLabel('继续方法草稿').selectOption(before.workspace);
 const editor=page.getByRole('region',{name:'方法方案编辑',exact:true});await expect(editor).toBeVisible();
 await expect(page.getByRole('dialog')).toHaveCount(0);await expect(editor).not.toContainText('权重合计 0');
 await expect(editor.getByLabel('认可此方法版本')).toHaveCount(0);await page.screenshot({path:evidencePath('method-empty-after.png')});
 const failed=page.waitForResponse(r=>r.url().endsWith('/publish'));
 await editor.getByRole('button',{name:'发布固定版本',exact:true}).click();expect((await failed).status()).toBe(422);
 await expect(editor).toContainText('请补充方法依据');await expect(editor).not.toContainText('TemplateSpec');await expect(editor).not.toContainText('input_value');
 await page.screenshot({path:evidencePath('method-publish-failure-after.png')});
 expect((await(await page.request.get('/api/method-workspaces/'+before.workspace)).json()).publication).toBeNull();
 await editor.getByLabel('方法名称',{exact:true}).fill('T08联合工程数学验证');
 await editor.getByRole('button',{name:'添加指标',exact:true}).click();
 for(const [label,value] of [['指标','质量'],['单位','1'],['下限','0'],['上限','1'],['权重','1']])await editor.getByLabel('第1项'+label,{exact:true}).fill(value);
 await editor.getByLabel('第1项方向',{exact:true}).selectOption('positive');
 if(!await editor.getByLabel('方法科学依据',{exact:true}).isVisible())await editor.getByText('方案说明与依据',{exact:true}).click();
 await editor.getByLabel('方法科学依据',{exact:true}).fill('工程数学验收：明确参考区间0至1、权重1、正向，不代表海岸业务评级。');
 await editor.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(editor.getByRole('status')).toHaveText('已保存');await page.screenshot({path:evidencePath('method-edit-after.png')});
 await page.reload();await page.getByLabel('继续方法草稿').selectOption(before.workspace);await expect(editor.getByLabel('第1项权重')).toHaveValue('1');
 const publication=page.waitForResponse(r=>r.url().endsWith('/publish'));await editor.getByRole('button',{name:'发布固定版本',exact:true}).click();const response=await publication;expect(response.status()).toBe(201);const published=await response.json();expect(published.template.approved).toBe(false);
 await expect(editor.getByRole('status')).toHaveText('已发布，待批准');await page.screenshot({path:evidencePath('method-published-after.png')});
 await editor.getByRole('button',{name:'批准第1版',exact:true}).click();await expect(editor.getByRole('status')).toHaveText('已批准第1版');
 await editor.getByRole('button',{name:'返回方法目录',exact:true}).click();
 const catalog=page.getByRole('region',{name:'方法方案',exact:true});await catalog.getByRole('button',{name:'查看方法',exact:true}).click();
 const detail=page.getByRole('dialog',{name:'方法版本详情',exact:true});const created=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/tasks');await detail.getByRole('button',{name:'以此方法新建任务',exact:true}).click();await expect(detail).not.toBeVisible();
 const taskId=(await(await created).json()).id; await expect.poll(async()=>(await(await page.request.get('/api/tasks/'+taskId)).json()).draft.method_id).toBe(published.template.id);
 let task=await(await page.request.get('/api/tasks/'+taskId)).json();expect(task.draft.method_id).toBe(published.template.id);expect(task.draft.options.method_revision).toBe(1);
 await page.getByRole('tab',{name:'输入 0',exact:true}).click();await page.getByRole('complementary',{name:'研究内容管理器',exact:true}).getByRole('button',{name:'添加资料',exact:true}).click();
 const importer=page.getByRole('dialog',{name:'添加研究输入',exact:true});await expect(importer.getByLabel('选择并导入资料',{exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(1);
 await expect(importer).toContainText('质量');await page.screenshot({path:evidencePath('one-click-task-import.png')});
 await importer.getByLabel('选择并导入资料',{exact:true}).setInputFiles({name:'联合数值工程夹具.csv',mimeType:'text/csv',buffer:Buffer.from('id,quality\n001,0.25\n002,0.75\n')});
 await expect(page.getByRole('tab',{name:'输入 1',exact:true})).toBeVisible();await importer.getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:/指标生产/}).click();
 await page.getByLabel('用途 table/id',{exact:true}).selectOption('identity');
 await page.getByLabel('科学含义 table/quality',{exact:true}).fill('质量');await page.getByLabel('单位 table/quality',{exact:true}).fill('1');await page.getByLabel('支撑 table/quality',{exact:true}).selectOption('point');
 await expect.poll(async()=>{task=await(await page.request.get('/api/tasks/'+taskId)).json();return task.draft.mapping.find((m:{field:string})=>m.field==='table/quality')?.support;}).toBe('point');
 const needed=await(await page.request.get('/api/tasks/'+taskId+'/input-requirements')).json();expect(needed.requirements[0].status).toBe('used');
 const executed=page.waitForResponse(r=>r.url().endsWith('/execute'));await page.getByRole('button',{name:'预检并执行',exact:true}).click();const runResponse=await executed;expect(runResponse.status()).toBe(202);const job=await runResponse.json();
 await expect.poll(async()=> (await(await page.request.get('/api/jobs/'+job.id)).json()).status,{timeout:90000}).toBe('succeeded');
 await expect(page.getByRole('table',{name:'观测结果',exact:true})).toBeVisible();await expect(page.getByRole('table',{name:'观测结果',exact:true})).toContainText('0.25');
 const output=await(await page.request.get('/api/jobs/'+job.id+'/result')).json();expect(output.data.scores).toEqual([.25,.75]);
 await page.screenshot({path:evidencePath('joint-numeric-result.png')});
 const stored=await(await page.request.get('/api/method-workspaces/'+before.workspace)).json();
 await writeFile(evidencePath('joint-flow.json'),JSON.stringify({build:'unified-business-dev14',project:before.project,workspace:before.workspace,task:taskId,method:published.template.id,method_revision:1,job:job.id,stored,requirements:needed,result:output,requests,measurements:{method_fields:7,direction_choices:1,publish_action:1,approval_action:1,explicit_apply:1,upload_chooser:1,reuploads:0,mapping_fields:2,mapping_choices:2},scope:'Isolated engineering numerical fixture; no business or spatial validation claim'},null,2));
});
