import { test, expect } from '@playwright/test';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { evidenceDirectory, evidencePath } from './evidence';

test('N03 actual418MB source explicit snapshot, direct map, fixed original bytes',async({page})=>{
  test.setTimeout(180000);
  if(!process.env.COASTMAS_NEXT_TEST_URL?.endsWith(':58013'))throw new Error('Isolated58013 only');
  const access=JSON.parse(await readFile(process.env.COASTMAS_NEXT_ACCESS_FILE!,'utf8'));
  await mkdir(evidenceDirectory,{recursive:true});await page.setViewportSize({width:1440,height:900});
  await page.goto('/library');await page.getByLabel('邮箱',{exact:true}).fill(access.email);await page.getByLabel('密码',{exact:true}).fill(access.password);await page.getByRole('button',{name:'登录',exact:true}).click();
  await expect(page.getByRole('button',{name:'新建研究',exact:true})).toBeVisible();
  const session=await (await page.request.get('/api/session')).json(),headers={'X-CSRF-Token':session.csrf};
  const project=await (await page.request.post('/api/projects',{headers,data:{name:'真实来源快照验收-'+Date.now()}})).json();
  const sources=await (await page.request.get(`/api/projects/${project.id}/local-sources`)).json();expect(sources).toHaveLength(1);expect(sources[0].granted).toBe(false);
  expect((await page.request.get(`/api/projects/${project.id}/local-sources/${sources[0].id}/files`)).status()).toBe(403);
  expect((await page.request.post(`/api/projects/${project.id}/local-sources/${sources[0].id}/grant`,{headers})).ok()).toBeTruthy();
  await page.goto('/library?project='+project.id);await page.getByRole('button',{name:'导入资料',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'导入项目资料',exact:true});
  await dialog.getByRole('button',{name:'已授权来源',exact:true}).click();
  const source=dialog.getByRole('region',{name:'已授权来源导入',exact:true});
  await source.getByRole('button',{name:'zhusanjiao/',exact:true}).click();await source.getByRole('button',{name:'土地利用/',exact:true}).click();
  await source.getByLabel('搜索当前目录').fill('PRD_distance_water.tif');
  await expect(source.locator('tbody tr')).toHaveCount(3);
  await expect(source.getByLabel('选择 PRD_distance_water.tif.aux.xml',{exact:true})).toBeVisible();
  await expect(source.getByLabel('选择 PRD_distance_water.tif.ovr',{exact:true})).toBeVisible();
  const empty=await (await page.request.get(`/api/projects/${project.id}/catalog`)).json();expect(empty.total).toBe(0);
  await source.getByLabel('选择 PRD_distance_water.tif',{exact:true}).check();await source.getByRole('button',{name:'导入选中资料',exact:true}).click();
  await expect(source.getByText('已进入资料库',{exact:false})).toBeVisible({timeout:120000});
  const listing=await (await page.request.get(`/api/projects/${project.id}/source-snapshots`)).json();expect(listing).toHaveLength(1);expect(listing[0].status).toBe('ready');
  const asset=await (await page.request.get(`/api/assets/${listing[0].asset_id}`)).json();expect(asset.size).toBe(418826745);
  await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  await expect(page.locator('.research-map .maplibregl-canvas')).toBeVisible();
  await page.getByRole('button',{name:'关闭目录',exact:true}).click();
  await expect(page.getByRole('button',{name:'新建研究',exact:true})).toBeVisible();
  const tasks=await (await page.request.get(`/api/management/catalog/tasks?project=${project.id}`)).json();expect(tasks.total).toBe(0);
  const view=await (await page.request.get(`/api/assets/${asset.id}/view`)).json();expect(view.georeference_status).toBe('located');
  await expect(page.locator('.research-map [data-state=ready]')).toBeVisible({timeout:60000});
  await page.screenshot({path:evidencePath('real-source-direct-map-1440.png')});
  await writeFile(evidencePath('real-source-snapshot.json'),JSON.stringify({project:project.id,asset_id:asset.id,source_relative:'zhusanjiao/土地利用/PRD_distance_water.tif',size:asset.size,sha256:asset.sha256,member_count:asset.facts.logical_package.members.length,source_connection_did_not_grant:true,browsing_did_not_import:true,taskCount:0,fieldsFilled:0,selections:1,importActions:1,view},null,2));
});
