import { test, expect } from '@playwright/test';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { evidenceDirectory, evidencePath } from './evidence';

test('N06 method create, persisted edit, publish, clone, mapped import and fixed application',async({page})=>{
  test.setTimeout(120000);
  if(!process.env.COASTMAS_NEXT_TEST_URL?.endsWith(':58013'))throw new Error('Isolated58013 only');
  const access=JSON.parse(await readFile(process.env.COASTMAS_NEXT_ACCESS_FILE!,'utf8'));
  await mkdir(evidenceDirectory,{recursive:true});await page.setViewportSize({width:1440,height:900});
  await page.goto('/methods');await page.getByLabel('邮箱',{exact:true}).fill(access.email);await page.getByLabel('密码',{exact:true}).fill(access.password);await page.getByRole('button',{name:'登录',exact:true}).click();
  await expect(page.getByRole('button',{name:'新建研究',exact:true})).toBeVisible();
  const session=await (await page.request.get('/api/session')).json(),headers={'X-CSRF-Token':session.csrf};
  const project=await (await page.request.post('/api/projects',{headers,data:{name:'方法闭环验收-'+Date.now()}})).json();
  const task=await (await page.request.post('/api/tasks',{headers,data:{project_id:project.id,goal:'comprehensive-assessment',title:'方法固定引用验收'}})).json();
  await page.goto(`/tasks/${task.id}?project=${project.id}`);
  await page.getByRole('link',{name:'方法方案',exact:true}).click();
  const catalog=page.getByRole('region',{name:'方法方案',exact:true});
  await catalog.getByRole('button',{name:'新建',exact:true}).click();
  const editor=page.getByRole('region',{name:'方法方案编辑',exact:true});await expect(editor).toBeVisible();
  await editor.getByLabel('方法名称',{exact:true}).fill('工程质量综合方法');
  if(!await editor.getByLabel('方法科学依据').isVisible())await editor.getByText('方案说明与依据',{exact:true}).click();await editor.getByLabel('方法科学依据',{exact:true}).fill('自动验收工程方法；参考区间0至1，明确权重1，不代表海岸业务结论。');
  await editor.getByRole('button',{name:'添加指标',exact:true}).click();
  await expect(editor.getByLabel('第1项方向',{exact:true})).toHaveValue('');
  for(const [label,value] of [['指标','质量'],['单位','1'],['下限','0'],['上限','1'],['权重','1']])await editor.getByLabel('第1项'+label,{exact:true}).fill(value);
  await editor.getByLabel('第1项方向',{exact:true}).selectOption('positive');
  await editor.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(editor.getByRole('status')).toHaveText('已保存');
  await editor.getByRole('button',{name:'返回方法目录',exact:true}).click();await page.reload();
  const draftOption=page.getByLabel('继续方法草稿').locator('option').filter({hasText:'工程质量综合方法'});const editId=await draftOption.getAttribute('value');if(!editId)throw new Error('No durable method draft');
  await page.getByLabel('继续方法草稿').selectOption(editId);await expect(editor.getByLabel('第1项权重')).toHaveValue('1');
  await editor.getByRole('button',{name:'发布固定版本',exact:true}).click();await expect(editor.getByRole('status')).toHaveText('已发布，待批准');await editor.getByRole('button',{name:'批准第1版',exact:true}).click();await expect(editor.getByRole('status').first()).toHaveText('已批准第1版');
  await page.screenshot({path:evidencePath('method-editor-1440.png')});
  await editor.getByRole('button',{name:'返回方法目录',exact:true}).click();
  await expect(catalog.locator('tbody tr')).toHaveCount(1);
  const before=await (await page.request.get(`/api/tasks/${task.id}`)).json();
  await catalog.getByRole('button',{name:'查看方法',exact:true}).click();
  const detail=page.getByRole('dialog',{name:'方法版本详情',exact:true});await expect(detail).toBeVisible();
  expect((await (await page.request.get(`/api/tasks/${task.id}`)).json()).revision).toBe(before.revision);
  await detail.getByRole('button',{name:'应用到当前任务',exact:true}).click();await expect(detail).not.toBeVisible();
  const applied=await (await page.request.get(`/api/tasks/${task.id}`)).json();expect(applied.draft.options.method_revision).toBe(1);expect(applied.revision).toBe(before.revision+1);
  await catalog.getByRole('button',{name:'克隆',exact:true}).click();await expect(editor.getByLabel('方法名称')).toHaveValue('工程质量综合方法 · 副本');await editor.getByRole('button',{name:'返回方法目录',exact:true}).click();
  await catalog.getByRole('button',{name:'导入方法',exact:true}).click();
  const importer=page.getByRole('dialog',{name:'导入方法方案',exact:true});
  await importer.getByLabel('选择方案文件').setInputFiles({name:'指标表.csv',mimeType:'text/csv',buffer:Buffer.from('指标,单位,下限,上限,方向,权重\n压力,1,0,10,负向,1\n')});
  await importer.getByRole('button',{name:'读取并建立草稿',exact:true}).click();await expect(editor).toBeVisible();
  await expect(editor.getByLabel('方法科学依据')).toHaveValue('');await expect(editor.getByLabel('第1项方向')).toHaveValue('negative');await editor.getByRole('button',{name:'返回方法目录',exact:true}).click();
  const all=await (await page.request.get(`/api/management/catalog/tasks?project=${project.id}`)).json();expect(all.total).toBe(1);
  await page.screenshot({path:evidencePath('method-library-1440.png')});
  await writeFile(evidencePath('method-flow.json'),JSON.stringify({project:project.id,task:task.id,method:applied.draft.method_id,methodRevision:1,taskCount:all.total,draftId:editId,creationMeasurement:{filledFields:7,scientificDirectionSelections:1,approvalActions:1},browseDidNotApply:true,serverDraftRestored:true,csvImportPreservedMissingBasis:true},null,2));
});
