import { test, expect } from '@playwright/test';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { evidenceDirectory, evidencePath } from './evidence';

test('N02–N05 actual upload, attach, management and resizable Dock',async({page})=>{
  test.setTimeout(120000);
  if(!process.env.COASTMAS_NEXT_TEST_URL?.endsWith(':58013')) throw new Error('Isolated58013 only');
  const access=JSON.parse(await readFile(process.env.COASTMAS_NEXT_ACCESS_FILE!,'utf8'));
  await mkdir(evidenceDirectory,{recursive:true});
  const requests:{method:string,path:string,body:unknown,status?:number}[]=[];
  page.on('request',request=>{
    if(request.url().includes('/inputs:attach')) requests.push({method:request.method(),path:new URL(request.url()).pathname,body:request.postDataJSON()});
  });
  await page.setViewportSize({width:1440,height:900});
  await page.goto('/management/settings?project='+access.project_id);
  await page.getByLabel('邮箱',{exact:true}).fill(access.email);await page.getByLabel('密码',{exact:true}).fill(access.password);
  await page.getByRole('button',{name:'登录',exact:true}).click();
  await expect(page.getByRole('heading',{name:'数据源与系统设置',exact:true})).toBeVisible();
  await expect(page.getByLabel('初始密码',{exact:true})).toHaveCount(0);
  await expect(page.getByLabel('新项目名称',{exact:true})).toHaveCount(0);
  await page.screenshot({path:evidencePath('after-settings-1440.png')});
  const login=await (await page.request.get('/api/session')).json();
  const isolated=await (await page.request.post('/api/projects',{headers:{'X-CSRF-Token':login.csrf},data:{name:'U验收-'+Date.now()}})).json();access.project_id=isolated.id;
  await page.goto('/library?project='+access.project_id);
  await page.getByRole('button',{name:'导入资料',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'导入项目资料',exact:true});
  const fixture=process.env.COASTMAS_NEXT_FIXTURE_DIR!;
  await dialog.getByLabel('选择并导入资料',{exact:true}).setInputFiles(['coast.tif','coast.tfw','coast.tif.aux.xml','coast.tif.ovr'].map(name=>join(fixture,name)));
  await expect(dialog.getByRole('status')).toContainText('逻辑资料已受管');
  await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  const catalog=page.getByRole('region',{name:'资料目录',exact:true});
  await expect(catalog.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('.research-map .maplibregl-canvas')).toBeVisible();
  const initialHandle=page.getByRole('separator',{name:'调整目录高度'});
  const beforeHeight=Number(await initialHandle.getAttribute('aria-valuenow'));
  const box=await initialHandle.boundingBox();if(!box)throw new Error('splitter not measurable');
  await page.mouse.move(box.x+box.width/2,box.y+5);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y-95,{steps:12});await page.mouse.up();
  await expect.poll(async()=>Number(await initialHandle.getAttribute('aria-valuenow'))).toBe(beforeHeight+100);
  const heightAfter=await initialHandle.getAttribute('aria-valuenow');
  await page.getByRole('button',{name:'最大化表格',exact:true}).click();
  await expect(page.locator('.research-workspace')).toHaveAttribute('data-drawer','maximized');
  await page.getByRole('button',{name:'恢复面板',exact:true}).click();
  await expect(initialHandle).toHaveAttribute('aria-valuenow',heightAfter!);
  await initialHandle.focus();await initialHandle.press('ArrowDown');
  await expect(initialHandle).toHaveAttribute('aria-valuenow',String(beforeHeight+76));
  await page.screenshot({path:evidencePath('after-data-dock-1440.png')});
  await catalog.getByRole('button',{name:'加入当前任务',exact:true}).click();
  await page.getByRole('dialog',{name:'选择加入的研究',exact:true}).getByRole('button',{name:'新建研究并加入',exact:true}).click();
  const create=page.getByRole('dialog',{name:'新建研究任务',exact:true});
  await expect(create.getByLabel('研究目标')).toHaveValue('comprehensive-assessment');
  await expect(create.getByRole('option')).toHaveCount(5);
  await create.getByLabel('任务名称（可选）').fill('N02 真实加入事务');
  await create.getByRole('button',{name:'创建并继续',exact:true}).click();
  await expect(create).not.toBeVisible();
  await expect(page.getByRole('tab',{name:'输入 1',exact:true})).toBeVisible();
  await expect(page.locator('.research-map .maplibregl-canvas')).toBeVisible();
  const taskId=new URL(page.url()).pathname.split('/').pop()!;
  const first=(await page.request.get('/api/tasks/'+taskId));expect(first.ok()).toBeTruthy();
  const saved=await first.json();expect(saved.draft.selection).toHaveLength(1);expect(saved.revision).toBe(2);
  await page.reload();await expect(page.getByRole('tab',{name:'输入 1',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'数据资源',exact:true}).click();
  await expect(catalog.getByRole('button',{name:'已加入',exact:true})).toBeDisabled();
  const session=await (await page.request.get('/api/session')).json();
  const headers={'X-CSRF-Token':session.csrf};
  const plan=await (await page.request.post('/api/management/catalog/tasks/selections',{headers,data:{ids:[taskId],action:'recycle'}})).json();
  const applied=await (await page.request.post('/api/management/selections/'+plan.id+'/apply',{headers})).json();expect(applied.succeeded).toBe(1);
  await page.getByRole('button',{name:'新建研究',exact:true}).click();
  await create.getByLabel('任务名称（可选）').fill('N02 回收旧研究后的新研究');
  await create.getByRole('button',{name:'创建并继续',exact:true}).click();await expect(create).not.toBeVisible();
  await expect(page.getByRole('button',{name:'查看或编辑研究名称',exact:true})).toContainText('回收旧研究后的新研究');
  const freshId=new URL(page.url()).pathname.split('/').pop()!;expect(freshId).not.toBe(taskId);
  await page.getByRole('link',{name:'数据资源',exact:true}).click();
  await catalog.getByRole('button',{name:'加入当前任务',exact:true}).click();await expect(catalog.getByRole('button',{name:'已加入',exact:true})).toBeDisabled();
  const fresh=await (await page.request.get('/api/tasks/'+freshId)).json();expect(fresh.draft.selection).toHaveLength(1);
  const assetId=fresh.draft.selection[0].asset_id;
  const point=await (await page.request.post(`/api/assets/${assetId}/inspect`,{headers,data:{longitude:113.005,latitude:22.995}})).json();expect(point.stored_value).toBe(0);
  const download=await page.request.get(`/api/assets/${assetId}/download`);expect(download.headers()['content-type']).toContain('zip');
  const measured=[];
  for(const viewport of [{width:1440,height:900},{width:1366,height:768}]) {
    await page.setViewportSize(viewport);
    await page.screenshot({path:evidencePath(`after-workspace-${viewport.width}.png`)});
    const dimensions=await page.locator('.catalog-single-toolbar').evaluate(el=>({height:el.getBoundingClientRect().height,width:el.getBoundingClientRect().width,pageOverflow:document.documentElement.scrollWidth>innerWidth}));
    await expect(page.locator('.research-map .maplibregl-canvas')).toBeVisible();
    expect(dimensions.height).toBeLessThanOrEqual(44);expect(dimensions.pageOverflow).toBe(false);measured.push({viewport,...dimensions});
  }
  await writeFile(evidencePath('unified-core.json'),JSON.stringify({input:'engineering fixture, not business validation',taskId,freshId,assetId,requests,savedRevision:saved.revision,point,measured,settings_duplicates_removed:true,dock_drag_and_restore:true,grouped_members:4,asset_count:1},null,2));
});
